The objective of this notebook is to compare my (incorrect) solution to the one provided by the course. 

In [56]:
using JuMP

### Initialize the variables

In [32]:
# My way:
m = Model()
@variable(m, x[1:9,1:9,1:9], Bin)

9×9×9 Array{JuMP.Variable,3}:
[:, :, 1] =
 x[1,1,1]  x[1,2,1]  x[1,3,1]  x[1,4,1]  …  x[1,7,1]  x[1,8,1]  x[1,9,1]
 x[2,1,1]  x[2,2,1]  x[2,3,1]  x[2,4,1]     x[2,7,1]  x[2,8,1]  x[2,9,1]
 x[3,1,1]  x[3,2,1]  x[3,3,1]  x[3,4,1]     x[3,7,1]  x[3,8,1]  x[3,9,1]
 x[4,1,1]  x[4,2,1]  x[4,3,1]  x[4,4,1]     x[4,7,1]  x[4,8,1]  x[4,9,1]
 x[5,1,1]  x[5,2,1]  x[5,3,1]  x[5,4,1]     x[5,7,1]  x[5,8,1]  x[5,9,1]
 x[6,1,1]  x[6,2,1]  x[6,3,1]  x[6,4,1]  …  x[6,7,1]  x[6,8,1]  x[6,9,1]
 x[7,1,1]  x[7,2,1]  x[7,3,1]  x[7,4,1]     x[7,7,1]  x[7,8,1]  x[7,9,1]
 x[8,1,1]  x[8,2,1]  x[8,3,1]  x[8,4,1]     x[8,7,1]  x[8,8,1]  x[8,9,1]
 x[9,1,1]  x[9,2,1]  x[9,3,1]  x[9,4,1]     x[9,7,1]  x[9,8,1]  x[9,9,1]

[:, :, 2] =
 x[1,1,2]  x[1,2,2]  x[1,3,2]  x[1,4,2]  …  x[1,7,2]  x[1,8,2]  x[1,9,2]
 x[2,1,2]  x[2,2,2]  x[2,3,2]  x[2,4,2]     x[2,7,2]  x[2,8,2]  x[2,9,2]
 x[3,1,2]  x[3,2,2]  x[3,3,2]  x[3,4,2]     x[3,7,2]  x[3,8,2]  x[3,9,2]
 x[4,1,2]  x[4,2,2]  x[4,3,2]  x[4,4,2]     x[4,7,2]  x[4,8,2]  x[4,9

In [33]:
# Their way:
sudoku = Model()
@defVar(sudoku, x[i=1:9, j=1:9, k=1:9], Bin)

9×9×9 Array{JuMP.Variable,3}:
[:, :, 1] =
 x[1,1,1]  x[1,2,1]  x[1,3,1]  x[1,4,1]  …  x[1,7,1]  x[1,8,1]  x[1,9,1]
 x[2,1,1]  x[2,2,1]  x[2,3,1]  x[2,4,1]     x[2,7,1]  x[2,8,1]  x[2,9,1]
 x[3,1,1]  x[3,2,1]  x[3,3,1]  x[3,4,1]     x[3,7,1]  x[3,8,1]  x[3,9,1]
 x[4,1,1]  x[4,2,1]  x[4,3,1]  x[4,4,1]     x[4,7,1]  x[4,8,1]  x[4,9,1]
 x[5,1,1]  x[5,2,1]  x[5,3,1]  x[5,4,1]     x[5,7,1]  x[5,8,1]  x[5,9,1]
 x[6,1,1]  x[6,2,1]  x[6,3,1]  x[6,4,1]  …  x[6,7,1]  x[6,8,1]  x[6,9,1]
 x[7,1,1]  x[7,2,1]  x[7,3,1]  x[7,4,1]     x[7,7,1]  x[7,8,1]  x[7,9,1]
 x[8,1,1]  x[8,2,1]  x[8,3,1]  x[8,4,1]     x[8,7,1]  x[8,8,1]  x[8,9,1]
 x[9,1,1]  x[9,2,1]  x[9,3,1]  x[9,4,1]     x[9,7,1]  x[9,8,1]  x[9,9,1]

[:, :, 2] =
 x[1,1,2]  x[1,2,2]  x[1,3,2]  x[1,4,2]  …  x[1,7,2]  x[1,8,2]  x[1,9,2]
 x[2,1,2]  x[2,2,2]  x[2,3,2]  x[2,4,2]     x[2,7,2]  x[2,8,2]  x[2,9,2]
 x[3,1,2]  x[3,2,2]  x[3,3,2]  x[3,4,2]     x[3,7,2]  x[3,8,2]  x[3,9,2]
 x[4,1,2]  x[4,2,2]  x[4,3,2]  x[4,4,2]     x[4,7,2]  x[4,8,2]  x[4,9

### Load the data. 

I took the inital conditions of the soduku problem and loaded them as constraints.

In [34]:
using JuMP
m = Model()

@variable(m, x[1:9,1:9,1:9], Bin)

# Need to set some initial conditions, do so in a constraint
# Referred to as C1 in the exercise
@constraint(m, x[1,1,5] == 1)
@constraint(m, x[2,1,6] == 1)
@constraint(m, x[4,1,8] == 1)
@constraint(m, x[5,1,4] == 1)
@constraint(m, x[6,1,7] == 1)
@constraint(m, x[1,2,3] == 1)
@constraint(m, x[3,2,9] == 1)
@constraint(m, x[7,2,6] == 1)
@constraint(m, x[3,3,8] == 1)
@constraint(m, x[2,4,1] == 1)
@constraint(m, x[5,4,8] == 1)
@constraint(m, x[8,4,4] == 1)
@constraint(m, x[1,5,7] == 1)
@constraint(m, x[2,5,9] == 1)
@constraint(m, x[4,5,6] == 1)
@constraint(m, x[6,5,2] == 1)
@constraint(m, x[8,5,1] == 1)
@constraint(m, x[9,5,8] == 1)
@constraint(m, x[2,6,5] == 1)
@constraint(m, x[5,6,3] == 1)
@constraint(m, x[8,6,9] == 1)
@constraint(m, x[7,7,2] == 1)
@constraint(m, x[3,8,6] == 1)
@constraint(m, x[7,8,8] == 1)
@constraint(m, x[9,8,7] == 1)
@constraint(m, x[4,9,3] == 1)
@constraint(m, x[5,9,1] == 1)
@constraint(m, x[6,9,6] == 1)
@constraint(m, x[8,9,5] == 1)
@constraint(m, x[9,9,9] == 1); # the semicolon supresses printing

x[9,9,9] = 1

In [35]:
# number of constraints
MathProgBase.numlinconstr(m::Model)

30

Here's how the course solution provided the data

In [57]:
init_sol = [5 3 0 0 7 0 0 0 0;
            6 0 0 1 9 5 0 0 0;
            0 9 8 0 0 0 0 6 0;
            8 0 0 0 6 0 0 0 3;
            4 0 0 8 0 3 0 0 1;
            7 0 0 0 2 0 0 0 6;
            0 6 0 0 0 0 2 8 0;
            0 0 0 4 1 9 0 0 5;
            0 0 0 0 8 0 0 7 9]

9×9 Array{Int64,2}:
 5  3  0  0  7  0  0  0  0
 6  0  0  1  9  5  0  0  0
 0  9  8  0  0  0  0  6  0
 8  0  0  0  6  0  0  0  3
 4  0  0  8  0  3  0  0  1
 7  0  0  0  2  0  0  0  6
 0  6  0  0  0  0  2  8  0
 0  0  0  4  1  9  0  0  5
 0  0  0  0  8  0  0  7  9

In [37]:
# number of constraints
MathProgBase.numlinconstr(sudoku::Model)

0

## Constraints

### First up: Every digit must appear in every row
### Every digit must appear in every column

In [38]:
# My way:
# Row
for j in 1:9
    for k in 1:9
        @constraint(m, sum{x[i,j,k], i in 1:9} == 1)
    end
end
# Column
for i in 1:9
    for k in 1:9
        @constraint(m, sum{x[i,j,k], j in 1:9} == 1)
    end
end

In [39]:
MathProgBase.numlinconstr(m::Model)

192

In [40]:
# Their way:
for ind = 1:9 # Each row, OR each column
for k = 1:9 # Each digit
# Sum across columns (j) - row constraint
@addConstraint(sudoku, sum{x[ind,j,k],j=1:9} == 1)
# Sum across rows (i) - column constraint
@addConstraint(sudoku, sum{x[i,ind,k],i=1:9} == 1)
end
end

In [41]:
MathProgBase.numlinconstr(sudoku::Model)

162

Looks equivalent thus far...

### Each number 1 - 9 must appear in 3 x 3 cells.

In [42]:
# My solution:
for a in 0:2
    for b in 0:2
        @constraint(m, sum{x[3*a + 1, 3*b + 1, k], k in 1:9} == 1)
        @constraint(m, sum{x[3*a + 1, 3*b + 2, k], k in 1:9} == 1)
        @constraint(m, sum{x[3*a + 1, 3*b + 3, k], k in 1:9} == 1)
        @constraint(m, sum{x[3*a + 2, 3*b + 1, k], k in 1:9} == 1)
        @constraint(m, sum{x[3*a + 2, 3*b + 2, k], k in 1:9} == 1)
        @constraint(m, sum{x[3*a + 2, 3*b + 3, k], k in 1:9} == 1)
        @constraint(m, sum{x[3*a + 3, 3*b + 1, k], k in 1:9} == 1)
        @constraint(m, sum{x[3*a + 3, 3*b + 2, k], k in 1:9} == 1)
        @constraint(m, sum{x[3*a + 3, 3*b + 3, k], k in 1:9} == 1)
    end
end

In [43]:
MathProgBase.numlinconstr(m::Model)

273

In [44]:
# Their solution:
for i = 1:3:7, j = 1:3:7, k = 1:9
# i is the top left row, j is the top left column
# For each 3x3 square, we sum from from row i to i+2 and column j to j+2
@addConstraint(sudoku, sum{x[r,c,k], r=i:i+2, c=j:j+2} == 1)
end

In [45]:
MathProgBase.numlinconstr(sudoku::Model)

243

### Every cell must contain a digit

In [46]:
# My solution:
for i in 1:9
    for j in 1:9
        @constraint(m, sum{x[i,j,k], k in 1:9} == 1)
    end
end


In [47]:
MathProgBase.numlinconstr(m::Model)

354

In [50]:
# Their solution:
for i = 1:9, j = 1:9
# If the space isn’t empty
if init_sol[i,j] != 0
# Then the corresponding variable for that digit and location must be 1
@addConstraint(sudoku, x[i,j,init_sol[i,j]] == 1)
end
end

In [51]:
MathProgBase.numlinconstr(sudoku::Model)

303

So now I have 51 additional constraints...

In [60]:
# Let's do these individually, build two new models
m2 = Model()
@variable(m2, x[1:9,1:9,1:9], Bin)
sudoku2 = Model()
@defVar(sudoku2, x[i=1:9, j=1:9, k=1:9], Bin)

for i in 1:9
    for j in 1:9
        @constraint(m2, sum{x[i,j,k], k in 1:9} == 1)
    end
end

for i = 1:9, j = 1:9
    # If the space isn’t empty
    if init_sol[i,j] != 0
    # Then the corresponding variable for that digit and location must be 1
    @addConstraint(sudoku2, x[i,j,init_sol[i,j]] == 1)
    end
end

println(MathProgBase.numlinconstr(m2::Model))
println(MathProgBase.numlinconstr(sudoku2::Model))



81
30


So this is what happened, my version adds 81 new constraints, whereas theirs only adds 30 -- the 30 inital solutions. Some of mine may be redundant...

## Solve

In [61]:
# My way:
solve(m)

#getvalue(x)
x_results = getvalue(x)
A = x_results[5,2,:]
B = x_results[3,6,:]
C = x_results[9,7,:]

println("A: ",A)
println("B: ",B)
println("C: ",C)
#x_results

LoadError: LoadError: No MIP solver detected. Try installing one of the following packages: "Cbc",  "GLPKMathProgInterface",  "Gurobi",  "CPLEX",  "Mosek",  and restarting Julia
while loading In[61], in expression starting on line 2

In [62]:
# Their way:
solve(sudoku)
# Get the values of x
x_val = getValue(x)
# Create a matrix to store the solution
sol = zeros(Int,9,9) # 9x9 matrix of integers
for i in 1:9, j in 1:9, k in 1:9
# There are numerical issue when solving integer programs, so the values
# may not be precisely 0 and 1.
# Occasionally, you might get solution is very close to 1 (say 0.9999)
# which indeed indicates 1,and solution is very close to 0 (say 0.1111)
# which indeed indicates 0.
# We can just round them to the nearest integer to make it easier
if round(Int, x_val[i,j,k]) == 1
sol[i,j] = k
end
end
println(sol)

LoadError: LoadError: No MIP solver detected. Try installing one of the following packages: "Cbc",  "GLPKMathProgInterface",  "Gurobi",  "CPLEX",  "Mosek",  and restarting Julia
while loading In[62], in expression starting on line 2